/* JobAI standalone vacancies page v1 */
(function(){
'use strict';
var T={ua:{nav:'Вакансії',title:'Вакансії у Словаччині',sub:'Шукайте актуальні пропозиції роботи безпосередньо в JobAI.',q:'Професія або компанія',loc:'Місто / район',all:'Усі категорії',min:'Мін. зарплата €',sort:'Сортування',newest:'За відповідністю',pay:'За зарплатою',found:'Знайдено',open:'Відкрити вакансію',empty:'За цими фільтрами вакансій немає.',updated:'Оновлено'},sk:{nav:'Pracovné ponuky',title:'Pracovné ponuky na Slovensku',sub:'Vyhľadávajte aktuálne pracovné ponuky priamo v JobAI.',q:'Profesia alebo firma',loc:'Mesto / okres',all:'Všetky kategórie',min:'Min. mzda €',sort:'Zoradenie',newest:'Podľa zhody',pay:'Podľa mzdy',found:'Nájdené',open:'Otvoriť ponuku',empty:'Pre tieto filtre nie sú ponuky.',updated:'Aktualizované'},en:{nav:'Jobs',title:'Jobs in Slovakia',sub:'Search current Slovak vacancies directly in JobAI.',q:'Profession or company',loc:'City / district',all:'All categories',min:'Min. salary €',sort:'Sort',newest:'By relevance',pay:'By salary',found:'Found',open:'Open vacancy',empty:'No vacancies match these filters.',updated:'Updated'}};
var DATA={jobs:[]};function lang(){var l=(localStorage.getItem('jobaiLanguage')||document.documentElement.lang||'ua').toLowerCase();return l.indexOf('sk')===0?'sk':l.indexOf('en')===0?'en':'ua';}function tr(){return T[lang()];}function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();}function sal(s){var a=String(s||'').replace(/\s/g,'').match(/\d+(?:[.,]\d+)?/);if(!a)return 0;var n=parseFloat(a[0].replace(',','.'));if(/hod|hour/i.test(s))n*=160;return n||0;}
function style(){if(document.getElementById('jpStyle'))return;var s=document.createElement('style');s.id='jpStyle';s.textContent='.jp-hero{padding:28px;border:1px solid #334155;border-radius:18px;background:linear-gradient(135deg,#172554,#111827);margin-bottom:18px}.jp-hero h1{margin:0 0 8px}.jp-hero p{margin:0;color:#cbd5e1}.jp-filters{display:grid;grid-template-columns:1.4fr 1fr 1fr .8fr 1fr;gap:9px;margin:18px 0}.jp-filters input,.jp-filters select{padding:11px;border-radius:10px;border:1px solid #475569;background:#172033;color:#e5e7eb;min-width:0}.jp-count{font-weight:800;margin:12px 0}.jp-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.jp-card{border:1px solid #334155;border-radius:15px;padding:17px;background:#172033}.jp-card h3{margin:8px 0}.jp-company{font-weight:700}.jp-meta{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.jp-chip{padding:6px 9px;border-radius:999px;background:#1e3a5f;font-size:13px}.jp-card a{display:inline-block;background:#1976d2;color:white;text-decoration:none;padding:9px 13px;border-radius:9px;font-weight:700;margin-top:6px}.jp-date{opacity:.65;font-size:12px;margin-top:12px}@media(max-width:900px){.jp-filters{grid-template-columns:1fr 1fr}.jp-grid{grid-template-columns:1fr}}@media(max-width:560px){.jp-filters{grid-template-columns:1fr}}';document.head.appendChild(s);}
function build(){if(document.getElementById('jobs'))return;var main=document.querySelector('main.container');if(!main)return;var sec=document.createElement('section');sec.id='jobs';sec.className='tab';sec.innerHTML='<div class="jp-hero"><h1 id="jpTitle"></h1><p id="jpSub"></p></div><div class="jp-filters"><input id="jpQ"><input id="jpLoc"><select id="jpCat"></select><input id="jpMin" type="number" min="0" step="100"><select id="jpSort"><option value="rel"></option><option value="pay"></option></select></div><div class="jp-count" id="jpCount"></div><div class="jp-grid" id="jpList"></div><div class="jp-date" id="jpDate"></div>';main.appendChild(sec);var nav=document.querySelector('.nav');var b=document.createElement('button');b.id='navJobs';b.onclick=function(){window.showTab('jobs');};nav.insertBefore(b,document.getElementById('navAnalysis'));['jpQ','jpLoc','jpMin'].forEach(function(id){document.getElementById(id).addEventListener('input',draw);});['jpCat','jpSort'].forEach(function(id){document.getElementById(id).addEventListener('change',draw);});style();translate();load();}
function translate(){var x=tr(),b=document.getElementById('navJobs');if(!b)return;b.textContent=x.nav;document.getElementById('jpTitle').textContent=x.title;document.getElementById('jpSub').textContent=x.sub;document.getElementById('jpQ').placeholder=x.q;document.getElementById('jpLoc').placeholder=x.loc;document.getElementById('jpMin').placeholder=x.min;var sort=document.getElementById('jpSort');sort.options[0].text=x.newest;sort.options[1].text=x.pay;fillCats();draw();}
function fillCats(){var s=document.getElementById('jpCat');if(!s)return;var keep=s.value,cats=[];DATA.jobs.forEach(function(j){if(j.category&&cats.indexOf(j.category)<0)cats.push(j.category);});cats.sort();s.innerHTML='<option value="">'+tr().all+'</option>'+cats.map(function(c){return '<option value="'+esc(c)+'">'+esc(c)+'</option>';}).join('');s.value=keep;}
function relevance(j){var pos=norm((document.getElementById('position')||{}).value),city=norm((document.getElementById('city')||{}).value),text=norm([j.title,j.category].join(' ')),m=50;if(pos){pos.split(/\W+/).filter(function(w){return w.length>2;}).forEach(function(w){if(text.indexOf(w)>=0)m+=8;});}if(city&&norm(j.location).indexOf(city)>=0)m+=10;return Math.min(99,m);}
function draw(){var list=document.getElementById('jpList');if(!list)return;var x=tr(),q=norm(document.getElementById('jpQ').value),loc=norm(document.getElementById('jpLoc').value),cat=document.getElementById('jpCat').value,min=parseFloat(document.getElementById('jpMin').value)||0,sort=document.getElementById('jpSort').value;var jobs=DATA.jobs.map(function(j){return Object.assign({},j,{_pay:sal(j.salary),_rel:relevance(j)});}).filter(function(j){return(!q||norm([j.title,j.employer,j.category].join(' ')).indexOf(q)>=0)&&(!loc||norm(j.location).indexOf(loc)>=0)&&(!cat||j.category===cat)&&(!min||j._pay>=min);});jobs.sort(function(a,b){return sort==='pay'?b._pay-a._pay:b._rel-a._rel;});document.getElementById('jpCount').textContent=x.found+': '+jobs.length;list.innerHTML=jobs.length?jobs.slice(0,60).map(function(j){return '<article class="jp-card"><div>🇸🇰 '+esc(j.category||'Práca')+' · <b>'+j._rel+'%</b></div><h3>'+esc(j.title)+'</h3><div class="jp-company">'+esc(j.employer||'')+'</div><div class="jp-meta"><span class="jp-chip">📍 '+esc(j.location||'Slovensko')+'</span><span class="jp-chip">💶 '+esc(j.salary||'—')+'</span></div><a target="_blank" rel="noopener noreferrer" href="'+esc(j.url)+'">'+x.open+'</a></article>';}).join(''):'<p>'+x.empty+'</p>';document.getElementById('jpDate').textContent=DATA.updatedAt?x.updated+': '+new Date(DATA.updatedAt).toLocaleString():'';}
function load(){fetch('jobs-data.json?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.json();}).then(function(d){DATA=d&&Array.isArray(d.jobs)?d:{jobs:[]};fillCats();draw();}).catch(function(){DATA={jobs:[]};draw();});}
var oldSet=window.setLanguage;window.setLanguage=function(l){if(typeof oldSet==='function')oldSet(l);setTimeout(translate,20);};var oldShow=window.showTab;window.showTab=function(n){if(typeof oldShow==='function')oldShow(n);if(n==='jobs'){var b=document.getElementById('navJobs');if(b)b.classList.add('active');draw();}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();
