/* JobAI standalone vacancies page v5 — structured location search + detailed resume matching */
(function(){
'use strict';
var T={
 ua:{nav:'Вакансії',title:'Вакансії у Словаччині',sub:'Актуальні вакансії з орієнтовною відповідністю вашому резюме.',q:'Професія або компанія',loc:'Місто / район',all:'Усі категорії',allRegions:'Усі краї',min:'Мін. зарплата €',sort:'Сортування',match:'За відповідністю',pay:'За зарплатою',found:'Знайдено',open:'Відкрити вакансію',analyze:'🔎 Аналізувати',empty:'За цими фільтрами вакансій немає.',updated:'Оновлено',fit:'Тільки вакансії, що підходять моєму резюме',from:'Від міста',allDistance:'Вся Словаччина',matchLabel:'Орієнтовна відповідність',skills:'Навички',langs:'Мови',experience:'Досвід',education:'Освіта',license:'Водійські права',notSpecified:'не вказано'},
 sk:{nav:'Pracovné ponuky',title:'Pracovné ponuky na Slovensku',sub:'Aktuálne ponuky s odhadovanou zhodou s vaším životopisom.',q:'Profesia alebo firma',loc:'Mesto / okres',all:'Všetky kategórie',allRegions:'Všetky kraje',min:'Min. mzda €',sort:'Zoradenie',match:'Podľa zhody',pay:'Podľa mzdy',found:'Nájdené',open:'Otvoriť ponuku',analyze:'🔎 Analyzovať',empty:'Pre tieto filtre nie sú ponuky.',updated:'Aktualizované',fit:'Len ponuky vhodné pre môj životopis',from:'Od mesta',allDistance:'Celé Slovensko',matchLabel:'Odhadovaná zhoda',skills:'Zručnosti',langs:'Jazyky',experience:'Prax',education:'Vzdelanie',license:'Vodičský preukaz',notSpecified:'neuvedené'},
 en:{nav:'Jobs',title:'Jobs in Slovakia',sub:'Current vacancies with estimated resume match.',q:'Profession or company',loc:'City / district',all:'All categories',allRegions:'All regions',min:'Min. salary €',sort:'Sort',match:'By match',pay:'By salary',found:'Found',open:'Open vacancy',analyze:'🔎 Analyze',empty:'No vacancies match these filters.',updated:'Updated',fit:'Only jobs matching my resume',from:'From city',allDistance:'All Slovakia',matchLabel:'Estimated match',skills:'Skills',langs:'Languages',experience:'Experience',education:'Education',license:'Driving licence',notSpecified:'not specified'}
};
var REGIONS=['Bratislavský kraj','Trnavský kraj','Trenčiansky kraj','Nitriansky kraj','Žilinský kraj','Banskobystrický kraj','Prešovský kraj','Košický kraj'];
var REGION_KEYS={'Bratislavský kraj':['bratislava','malacky','pezinok','senec'],'Trnavský kraj':['trnava','dunajska streda','galanta','hlohovec','piestany','senica','skalica'],'Trenčiansky kraj':['trencin','banovce nad bebravou','ilava','myjava','nove mesto nad vahom','partizanske','povazska bystrica','prievidza','puchov'],'Nitriansky kraj':['nitra','komarno','levice','nove zamky','sala','topolcany','zlate moravce'],'Žilinský kraj':['zilina','bytca','cadca','dolny kubin','kysucke nove mesto','liptovsky mikulas','martin','namestovo','ruzomberok','turcianske teplice','tvrdosin'],'Banskobystrický kraj':['banska bystrica','banska stiavnica','brezno','detva','krupina','lucenec','poltar','revuca','rimavska sobota','velky krtis','zvolen','ziar nad hronom','zarnovica'],'Prešovský kraj':['presov','bardejov','humenne','kezmarok','levoca','medzilaborce','poprad','sabinov','snina','stara lubovna','stropkov','svidnik','vranov nad toplou'],'Košický kraj':['kosice','michalovce','roznava','sobrance','spisska nova ves','trebisov','gelnica']};
var CITIES={'bratislava':[48.1486,17.1077],'trnava':[48.3774,17.5883],'trencin':[48.8945,18.0444],'nitra':[48.3061,18.0764],'zilina':[49.2231,18.7394],'banska bystrica':[48.7363,19.1462],'presov':[48.9984,21.2339],'kosice':[48.7164,21.2611],'martin':[49.0665,18.9239],'poprad':[49.0594,20.2975],'prievidza':[48.7745,18.6275],'zvolen':[48.5762,19.1371],'nove zamky':[47.9854,18.1619],'komarno':[47.7636,18.1226],'levice':[48.2156,18.6071],'dunajska streda':[47.9927,17.6121],'galanta':[48.1900,17.7275],'senec':[48.2194,17.4004],'pezinok':[48.2899,17.2666],'malacky':[48.4360,17.0219],'povazska bystrica':[49.1217,18.4217],'puchov':[49.1249,18.3255],'cadca':[49.4380,18.7889],'ruzomberok':[49.0748,19.3075],'liptovsky mikulas':[49.0811,19.6192],'dolny kubin':[49.2094,19.3034],'namestovo':[49.4079,19.4803],'bardejov':[49.2920,21.2753],'humenne':[48.9371,21.9163],'michalovce':[48.7543,21.9195],'trebisov':[48.6286,21.7195],'spisska nova ves':[48.9446,20.5615],'roznava':[48.6601,20.5376],'lucenec':[48.3325,19.6671],'rimavska sobota':[48.3828,20.0224],'brezno':[48.8040,19.6434],'zarnovica':[48.4812,18.7164],'ziar nad hronom':[48.5918,18.8496],'topolcany':[48.5636,18.1671],'partizanske':[48.6286,18.3846],'piestany':[48.5918,17.8272],'senica':[48.6792,17.3668],'skalica':[48.8449,17.2263]};
var DATA={jobs:[]};
function lang(){var l=(localStorage.getItem('jobaiLanguage')||document.documentElement.lang||'ua').toLowerCase();return l.indexOf('sk')===0?'sk':l.indexOf('en')===0?'en':'ua';}
function tr(){return T[lang()];}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9+#а-яіїєґ\s-]/gi,' ').replace(/\s+/g,' ').trim();}
function arr(v){return Array.isArray(v)?v.filter(Boolean):[];}
function val(id){var e=document.getElementById(id);return e&&'value' in e?e.value:'';}
function sal(s){var a=String(s||'').replace(/\s/g,'').match(/\d+(?:[.,]\d+)?/);if(!a)return 0;var n=parseFloat(a[0].replace(',','.'));if(/hod|hour/i.test(s))n*=160;return n||0;}
function jobGeo(j){return [j&&j.city,j&&j.district,j&&j.region,j&&j.postalCode,j&&j.location].filter(Boolean).join(' ');}
function regionForLocation(loc){var n=norm(loc),hit='';REGIONS.some(function(r){return REGION_KEYS[r].some(function(k){if(n.indexOf(norm(k))>=0){hit=r;return true;}return false;});});return hit;}
function cityCoord(text){var n=norm(text),hit=null;Object.keys(CITIES).some(function(k){if(n.indexOf(k)>=0){hit=CITIES[k];return true;}return false;});return hit;}
function km(a,b){if(!a||!b)return null;var R=6371,dLat=(b[0]-a[0])*Math.PI/180,dLon=(b[1]-a[1])*Math.PI/180,la1=a[0]*Math.PI/180,la2=b[0]*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return Math.round(R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)));}
function tokens(s){var stop=['praca','pracovne','ponuka','ponuky','zamestnanec','zamestnanie','the','and','with','for','resume','životopis','резюме'];return norm(s).split(' ').filter(function(w){return w.length>2&&stop.indexOf(w)<0;});}
function overlapScore(required,cv){var req=tokens(required),have=tokens(cv);if(!req.length)return null;var uniq=req.filter(function(x,i){return req.indexOf(x)===i;});var hit=uniq.filter(function(x){return have.indexOf(x)>=0;}).length;return Math.round(hit/uniq.length*100);}
function cvText(){var s=[val('position'),val('profile'),val('skills'),val('languages'),val('city')].join(' ');if(Array.isArray(window.experiences))s+=' '+JSON.stringify(window.experiences);if(Array.isArray(window.educations))s+=' '+JSON.stringify(window.educations);return s;}
function detailScore(j){var cv=cvText(),parts=[];
 var role=overlapScore([j.title,j.category,j.searchTerm].join(' '),val('position')+' '+cv); if(role!==null)parts.push({key:'role',score:Math.max(20,role),w:30});
 var skillsText=arr(j.computerSkills).join(' ')+' '+(j.description||''); var skills=overlapScore(skillsText,val('skills')+' '+cv); if(arr(j.computerSkills).length)parts.push({key:'skills',score:skills===null?0:skills,w:30});
 var langsText=arr(j.languages).join(' ')+(String(j.slovakRequired||'').toLowerCase()==='áno'?' slovenčina':''); var langs=overlapScore(langsText,val('languages')+' '+cv); if(norm(langsText))parts.push({key:'langs',score:langs===null?0:langs,w:15});
 if(norm(j.experience)){var ex=overlapScore(j.experience,cv);parts.push({key:'experience',score:ex===null?40:Math.max(25,ex),w:10});}
 if(arr(j.education).length){var ed=overlapScore(arr(j.education).join(' '),cv);parts.push({key:'education',score:ed===null?40:Math.max(20,ed),w:10});}
 if(arr(j.drivingLicenses).length){var lic=overlapScore(arr(j.drivingLicenses).join(' '),cv);parts.push({key:'license',score:lic===null?0:lic,w:5});}
 var totalW=parts.reduce(function(a,p){return a+p.w;},0),score=totalW?Math.round(parts.reduce(function(a,p){return a+p.score*p.w;},0)/totalW):50;
 var city=norm(val('city'));if(city&&norm(jobGeo(j)).indexOf(city)>=0)score=Math.min(99,score+4);score=Math.max(10,Math.min(99,score));
 var map={};parts.forEach(function(p){map[p.key]=p.score;});return {score:score,parts:map};}
function statusChip(label,score,specified){if(!specified)return '<span class="jp-req jp-na">'+esc(label)+': —</span>';var icon=score>=65?'✅':score>=35?'⚠️':'❌';return '<span class="jp-req">'+icon+' '+esc(label)+'</span>';}
function vacancyText(j){var lines=[j.title,j.employer&&('Zamestnávateľ: '+j.employer),j.location&&('Miesto výkonu práce: '+j.location),j.city&&('Mesto: '+j.city),j.district&&('Okres: '+j.district),j.region&&('Kraj: '+j.region),j.salary&&('Mzda: '+j.salary),j.description&&('Náplň práce: '+j.description),j.experience&&('Požadovaná prax: '+j.experience),arr(j.education).length&&('Požadované vzdelanie: '+arr(j.education).join(', ')),arr(j.languages).length&&('Požadované jazyky: '+arr(j.languages).join(', ')),arr(j.computerSkills).length&&('Počítačové zručnosti: '+arr(j.computerSkills).join(', ')),arr(j.drivingLicenses).length&&('Vodičské oprávnenie: '+arr(j.drivingLicenses).join(', ')),j.slovakRequired&&('Slovenčina nevyhnutná: '+j.slovakRequired)];return lines.filter(Boolean).join('\n');}
window.jobAIAnalyzeVacancy=function(i){var j=DATA.jobs[i];if(!j)return;var el=document.getElementById('jobText')||document.getElementById('job');if(el){el.value=vacancyText(j);try{el.dispatchEvent(new Event('input',{bubbles:true}));}catch(e){}}if(typeof window.showTab==='function')window.showTab('analysis');setTimeout(function(){if(typeof window.analyzeJob==='function')window.analyzeJob();},80);};
function style(){if(document.getElementById('jpStyle'))return;var s=document.createElement('style');s.id='jpStyle';s.textContent='.jp-hero{padding:28px;border:1px solid #334155;border-radius:18px;background:linear-gradient(135deg,#172554,#111827);margin-bottom:18px}.jp-hero h1{margin:0 0 8px}.jp-hero p{margin:0;color:#cbd5e1}.jp-filters{display:grid;grid-template-columns:1.25fr 1fr 1fr 1fr .8fr 1fr;gap:9px;margin:18px 0 10px}.jp-distance{display:grid;grid-template-columns:1fr .8fr;gap:9px;margin-bottom:10px}.jp-filters input,.jp-filters select,.jp-distance input,.jp-distance select{padding:11px;border-radius:10px;border:1px solid #475569;background:#172033;color:#e5e7eb;min-width:0}.jp-fit{display:flex;align-items:center;gap:8px;margin:8px 0 16px;font-weight:700}.jp-count{font-weight:800;margin:12px 0}.jp-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.jp-card{border:1px solid #334155;border-radius:15px;padding:17px;background:#172033}.jp-card h3{margin:8px 0}.jp-company{font-weight:700}.jp-meta,.jp-reqs{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.jp-chip,.jp-req{padding:6px 9px;border-radius:999px;background:#1e3a5f;font-size:13px}.jp-na{opacity:.7}.jp-actions{display:flex;gap:8px;flex-wrap:wrap}.jp-actions a,.jp-actions button{display:inline-block;background:#1976d2;color:white;border:0;text-decoration:none;padding:9px 13px;border-radius:9px;font-weight:700;cursor:pointer}.jp-actions button{background:#2563eb}.jp-date{opacity:.65;font-size:12px;margin-top:12px}@media(max-width:1050px){.jp-filters{grid-template-columns:1fr 1fr 1fr}}@media(max-width:900px){.jp-grid{grid-template-columns:1fr}}@media(max-width:560px){.jp-filters,.jp-distance{grid-template-columns:1fr}}';document.head.appendChild(s);}
function build(){if(document.getElementById('jobs'))return;var main=document.querySelector('main.container');if(!main)return;var sec=document.createElement('section');sec.id='jobs';sec.className='tab';sec.innerHTML='<div class="jp-hero"><h1 id="jpTitle"></h1><p id="jpSub"></p></div><div class="jp-filters"><input id="jpQ"><input id="jpLoc"><select id="jpRegion"></select><select id="jpCat"></select><input id="jpMin" type="number" min="0" step="100"><select id="jpSort"><option value="rel"></option><option value="pay"></option></select></div><div class="jp-distance"><input id="jpFrom"><select id="jpDistance"><option value=""></option><option value="10">10 km</option><option value="25">25 km</option><option value="50">50 km</option></select></div><label class="jp-fit"><input id="jpFit" type="checkbox"><span id="jpFitText"></span></label><div class="jp-count" id="jpCount"></div><div class="jp-grid" id="jpList"></div><div class="jp-date" id="jpDate"></div>';main.appendChild(sec);var nav=document.querySelector('.nav');if(nav&&!document.getElementById('navJobs')){var b=document.createElement('button');b.id='navJobs';b.onclick=function(){window.showTab('jobs');};nav.insertBefore(b,document.getElementById('navAnalysis'));}['jpQ','jpLoc','jpMin','jpFrom'].forEach(function(id){document.getElementById(id).addEventListener('input',draw);});['jpRegion','jpCat','jpSort','jpFit','jpDistance'].forEach(function(id){document.getElementById(id).addEventListener('change',draw);});style();translate();var cvCity=val('city');if(cvCity)document.getElementById('jpFrom').value=cvCity;load();}
function fillRegions(){var s=document.getElementById('jpRegion');if(!s)return;var keep=s.value;s.innerHTML='<option value="">'+tr().allRegions+'</option>'+REGIONS.map(function(r){return '<option value="'+esc(r)+'">'+esc(r)+'</option>';}).join('');s.value=keep;}
function fillCats(){var s=document.getElementById('jpCat');if(!s)return;var keep=s.value,cats=[];DATA.jobs.forEach(function(j){if(j.category&&cats.indexOf(j.category)<0)cats.push(j.category);});cats.sort();s.innerHTML='<option value="">'+tr().all+'</option>'+cats.map(function(c){return '<option value="'+esc(c)+'">'+esc(c)+'</option>';}).join('');s.value=keep;}
function translate(){var x=tr(),b=document.getElementById('navJobs');if(b)b.textContent=x.nav;if(!document.getElementById('jpTitle'))return;document.getElementById('jpTitle').textContent=x.title;document.getElementById('jpSub').textContent=x.sub;document.getElementById('jpQ').placeholder=x.q;document.getElementById('jpLoc').placeholder=x.loc;document.getElementById('jpMin').placeholder=x.min;document.getElementById('jpFrom').placeholder=x.from;document.getElementById('jpFitText').textContent=x.fit;var sort=document.getElementById('jpSort');sort.options[0].text=x.match;sort.options[1].text=x.pay;document.getElementById('jpDistance').options[0].text=x.allDistance;fillRegions();fillCats();draw();}
function draw(){var list=document.getElementById('jpList');if(!list)return;var x=tr(),q=norm(val('jpQ')),loc=norm(val('jpLoc')),region=val('jpRegion'),cat=val('jpCat'),min=parseFloat(val('jpMin'))||0,sort=val('jpSort'),fit=document.getElementById('jpFit').checked,maxKm=parseFloat(val('jpDistance'))||0,from=cityCoord(val('jpFrom'));var jobs=DATA.jobs.map(function(j,i){var geo=jobGeo(j),jc=cityCoord(geo),d=detailScore(j);return Object.assign({},j,{_i:i,_pay:sal(j.salary),_rel:d.score,_parts:d.parts,_region:j.region||regionForLocation(geo),_km:from&&jc?km(from,jc):null,_geo:geo});}).filter(function(j){var text=norm([j.title,j.employer,j.category,j.searchTerm,j.description].join(' ')),distOk=!maxKm||!from||(j._km!==null&&j._km<=maxKm);return(!q||text.indexOf(q)>=0)&&(!loc||norm(j._geo).indexOf(loc)>=0)&&(!region||j._region===region)&&(!cat||j.category===cat)&&(!min||j._pay>=min)&&(!fit||j._rel>=60)&&distOk;});jobs.sort(function(a,b){return sort==='pay'?b._pay-a._pay:b._rel-a._rel;});document.getElementById('jpCount').textContent=x.found+': '+jobs.length;list.innerHTML=jobs.length?jobs.slice(0,60).map(function(j){var p=j._parts||{};return '<article class="jp-card"><div class="jp-meta"><span class="jp-chip">'+esc(j.category||'—')+'</span><span class="jp-chip"><b>'+esc(x.matchLabel)+': '+j._rel+'%</b></span>'+(j._km!==null?'<span class="jp-chip">🚗 ~'+j._km+' km</span>':'')+'</div><h3>'+esc(j.title)+'</h3><div class="jp-company">'+esc(j.employer||'')+'</div><div>'+esc(j.location||'')+'</div><div class="jp-meta">'+(j.city?'<span class="jp-chip">📍 '+esc(j.city)+'</span>':'')+(j.salary?'<span class="jp-chip">💶 '+esc(j.salary)+' €</span>':'')+'</div><div class="jp-reqs">'+statusChip(x.skills,p.skills,arr(j.computerSkills).length>0)+statusChip(x.langs,p.langs,arr(j.languages).length>0||norm(j.slovakRequired)==='ano')+statusChip(x.experience,p.experience,!!norm(j.experience))+statusChip(x.education,p.education,arr(j.education).length>0)+statusChip(x.license,p.license,arr(j.drivingLicenses).length>0)+'</div><div class="jp-actions"><button type="button" onclick="jobAIAnalyzeVacancy('+j._i+')">'+x.analyze+'</button><a href="'+esc(j.url)+'" target="_blank" rel="noopener">'+x.open+'</a></div></article>';}).join(''):'<p>'+x.empty+'</p>';var updated=(DATA.updatedAt||'').replace('T',' ').slice(0,16);document.getElementById('jpDate').textContent=updated?x.updated+': '+updated:'';}
function load(){fetch('jobs-data.json?t='+Date.now(),{cache:'no-store'}).then(function(r){return r.json();}).then(function(d){DATA=Array.isArray(d)?{jobs:d}:(d&&Array.isArray(d.jobs)?d:{jobs:[]});fillCats();draw();}).catch(function(){DATA={jobs:[]};draw();});}
var oldShow=window.showTab;window.showTab=function(name){if(name==='jobs'){document.querySelectorAll('.tab').forEach(function(e){e.classList.remove('active');});var s=document.getElementById('jobs');if(s)s.classList.add('active');document.querySelectorAll('.nav button').forEach(function(b){b.classList.remove('active');});var nb=document.getElementById('navJobs');if(nb)nb.classList.add('active');return;}if(typeof oldShow==='function')return oldShow(name);};
var oldLang=window.setLanguage;window.setLanguage=function(l){if(typeof oldLang==='function')oldLang(l);setTimeout(translate,20);};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();