/* JobAI — tailor resume to vacancy v2: structured requirements */
(function(){
'use strict';
var T={ua:{btn:'🎯 Адаптувати резюме під вакансію',title:'Як адаптувати резюме',intro:'JobAI не вигадує досвід. Нижче — лише підказки на основі вашого резюме та вимог вакансії.',matched:'Що варто підкреслити',missing:'Що перевірити',position:'Посада',profile:'Профіль',skills:'Навички',langs:'Мови',experience:'Досвід',education:'Освіта',license:'Водійські права',none:'Явних збігів поки не знайдено.',truth:'Додавайте у резюме тільки те, що справді вмієте або робили.'},sk:{btn:'🎯 Prispôsobiť životopis pracovnej ponuke',title:'Ako prispôsobiť životopis',intro:'JobAI si nevymýšľa skúsenosti. Nižšie sú iba odporúčania podľa vášho životopisu a požiadaviek pracovnej ponuky.',matched:'Čo zvýrazniť',missing:'Čo skontrolovať',position:'Pozícia',profile:'Profil',skills:'Zručnosti',langs:'Jazyky',experience:'Prax',education:'Vzdelanie',license:'Vodičský preukaz',none:'Zatiaľ sa nenašli jasné zhody.',truth:'Do životopisu pridávajte iba to, čo skutočne ovládate alebo ste robili.'},en:{btn:'🎯 Tailor resume to job',title:'How to tailor your resume',intro:'JobAI does not invent experience. These suggestions use only your resume and the vacancy requirements.',matched:'What to emphasize',missing:'What to check',position:'Position',profile:'Profile',skills:'Skills',langs:'Languages',experience:'Experience',education:'Education',license:'Driving licence',none:'No clear matches found yet.',truth:'Only add things you genuinely know or have done.'}};
function lang(){var l=(localStorage.getItem('jobaiLanguage')||document.documentElement.lang||'ua').toLowerCase();return l.indexOf('sk')===0?'sk':l.indexOf('en')===0?'en':'ua';}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9+#а-яіїєґ\s-]/gi,' ').replace(/\s+/g,' ').trim();}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function val(id){var e=document.getElementById(id);return e&&e.value?e.value:'';}
function tokens(s){var stop=['the','and','with','for','you','your','are','praca','prace','pracovne','ponuka','ponuky','pozadujeme','vyhodou','resume','zivotopis','резюме'];return norm(s).split(/\s+/).filter(function(w){return w.length>2&&stop.indexOf(w)<0;});}
function overlap(required,have){var r=tokens(required),h=tokens(have);if(!r.length)return null;var u=r.filter(function(x,i){return r.indexOf(x)===i;}),hits=u.filter(function(x){return h.indexOf(x)>=0;});return {score:Math.round(hits.length/u.length*100),matched:hits,missing:u.filter(function(x){return hits.indexOf(x)<0;})};}
function field(text,labels){var lines=String(text||'').split(/\n+/);for(var i=0;i<lines.length;i++){for(var j=0;j<labels.length;j++){var n=norm(lines[i]),l=norm(labels[j]);if(n.indexOf(l)===0){var p=lines[i].indexOf(':');return p>=0?lines[i].slice(p+1).trim():'';}}}return '';}
function firstLine(text){return String(text||'').split(/\n+/).map(function(x){return x.trim();}).filter(Boolean)[0]||'';}
function parse(text){return {title:firstLine(text),skills:field(text,['Počítačové zručnosti','Skills','Навички']),langs:field(text,['Požadované jazyky','Požadované cudzie jazyky','Languages','Мови']),experience:field(text,['Požadovaná prax','Experience','Досвід']),education:field(text,['Požadované vzdelanie','Požadovaný stupeň vzdelania','Education','Освіта']),license:field(text,['Vodičské oprávnenie','Vodičské oprávnenia','Driving licence','Водійські права']),slovak:field(text,['Slovenčina nevyhnutná','Znalosť slovenského jazyka je nevyhnutná'])};}
function analyze(){var x=T[lang()],job=val('jobText')||val('job'),j=parse(job),resume=[val('position'),val('profile'),val('skills'),val('languages')].join(' ');if(Array.isArray(window.experiences))resume+=' '+JSON.stringify(window.experiences);if(Array.isArray(window.educations))resume+=' '+JSON.stringify(window.educations);var sections=[];function add(label,req,have){if(!norm(req))return;var o=overlap(req,have);sections.push({label:label,req:req,score:o?o.score:0,matched:o?o.matched:[],missing:o?o.missing:[]});}add(x.position,j.title,val('position')+' '+resume);add(x.skills,j.skills,val('skills')+' '+resume);var lr=j.langs+(norm(j.slovak)==='ano'?' slovenčina':'');add(x.langs,lr,val('languages')+' '+resume);add(x.experience,j.experience,resume);add(x.education,j.education,resume);add(x.license,j.license,resume);var good=sections.filter(function(s){return s.score>=65;}),check=sections.filter(function(s){return s.score<65;});var old=document.getElementById('jobaiTailorResult');if(old)old.remove();var box=document.createElement('div');box.id='jobaiTailorResult';function render(a,icon){if(!a.length)return '<p>'+x.none+'</p>';return '<ul>'+a.map(function(s){return '<li>'+icon+' <b>'+esc(s.label)+'</b>: '+esc(s.req)+' ('+s.score+'%)</li>';}).join('')+'</ul>';}var emphasis=good.map(function(s){return s.req;}).join(' · ');box.innerHTML='<h3>'+x.title+'</h3><p>'+x.intro+'</p><div class="jrt-grid"><section><strong>✅ '+x.matched+'</strong>'+render(good,'✅')+'</section><section><strong>🔎 '+x.missing+'</strong>'+render(check,'⚠️')+'</section></div><div class="jrt-actions"><p><b>'+x.position+':</b> '+esc(val('position')||j.title||'—')+'</p><p><b>'+x.profile+':</b> '+esc(emphasis||'—')+'</p><p><b>'+x.skills+':</b> '+esc(good.filter(function(s){return s.label===x.skills;}).map(function(s){return s.req;}).join(', ')||'—')+'</p></div><p class="jrt-truth">⚠️ '+x.truth+'</p>';var result=document.getElementById('analysisResult')||document.getElementById('analysis');result.appendChild(box);box.scrollIntoView({behavior:'smooth',block:'center'});}
function build(){var area=document.getElementById('analysisResult')||document.getElementById('analysis');if(!area||document.getElementById('jobaiTailorBtn'))return;var b=document.createElement('button');b.type='button';b.id='jobaiTailorBtn';b.className='btn primary';b.textContent=T[lang()].btn;b.addEventListener('click',analyze);area.parentNode.insertBefore(b,area);if(!document.getElementById('jobaiTailorStyle')){var s=document.createElement('style');s.id='jobaiTailorStyle';s.textContent='#jobaiTailorBtn{margin:12px 0}.jrt-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0}.jrt-grid section,.jrt-actions{padding:12px;border-radius:12px;background:rgba(59,130,246,.08)}#jobaiTailorResult{margin-top:16px;padding:16px;border:1px solid rgba(127,127,127,.3);border-radius:14px}.jrt-truth{font-size:13px;opacity:.8}@media(max-width:650px){.jrt-grid{grid-template-columns:1fr}}';document.head.appendChild(s);}}
var old=window.setLanguage;window.setLanguage=function(l){if(typeof old==='function')old(l);setTimeout(function(){var b=document.getElementById('jobaiTailorBtn');if(b)b.textContent=T[lang()].btn;},30);};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();
