/* JobAI resume hints v1 */
(function(){
'use strict';
var T={
ua:{title:'Підказка JobAI',truth:'Вказуйте лише реальний досвід і навички.',profile:'Напишіть 2–4 речення: хто ви, скільки маєте досвіду, з чим працювали і яку користь можете дати роботодавцю. Приклад: «CNC оператор з 4 роками досвіду. Працюю з Fanuc та Heidenhain, читаю технічні креслення, виконую контроль розмірів».',skills:'Додавайте конкретні навички, обладнання, програми, сертифікати та посвідчення. Краще: «Fanuc, Heidenhain, CMM, VZV», а не просто «відповідальний».',languages:'Для кожної мови вкажіть рівень: A1–C2 або рідна. Наприклад: «Українська — рідна, Словацька — B1, Англійська — A2».',position:'Вкажіть конкретну посаду, яку шукаєте. Наприклад: «CNC operátor», «Zvárač», «Skladník / VZV». Це покращує підбір вакансій.',experience:'Описуйте не лише обов’язки, а й результат: обладнання, матеріали, обсяг роботи, якість, швидкість, відповідальність. Формула: дія + інструмент/обладнання + результат.',education:'Вкажіть заклад, спеціальність і рік. Якщо маєте курси, сертифікати або професійні посвідчення — додайте їх у навички або опис профілю.'},
sk:{title:'Tip JobAI',truth:'Uvádzajte iba skutočné skúsenosti a zručnosti.',profile:'Napíšte 2–4 vety: kto ste, koľko máte praxe, s čím ste pracovali a akú hodnotu viete priniesť zamestnávateľovi. Príklad: „CNC operátor so 4 rokmi praxe. Pracujem s Fanuc a Heidenhain, čítam technické výkresy a kontrolujem rozmery.“',skills:'Uvádzajte konkrétne zručnosti, stroje, programy, certifikáty a oprávnenia. Lepšie: „Fanuc, Heidenhain, CMM, VZV“ než iba „zodpovedný“.',languages:'Pri každom jazyku uveďte úroveň A1–C2 alebo materinský jazyk. Napríklad: „Ukrajinčina — materinský jazyk, Slovenčina — B1, Angličtina — A2“.',position:'Uveďte konkrétnu pozíciu, ktorú hľadáte. Napríklad: „CNC operátor“, „Zvárač“, „Skladník / VZV“. Zlepší to výber ponúk.',experience:'Neopisujte iba povinnosti, ale aj výsledok: stroje, materiály, objem práce, kvalitu, rýchlosť či zodpovednosť. Vzorec: činnosť + nástroj/stroj + výsledok.',education:'Uveďte školu, odbor a rok. Kurzy, certifikáty alebo oprávnenia môžete doplniť do zručností alebo profilu.'},
en:{title:'JobAI tip',truth:'Only include experience and skills you genuinely have.',profile:'Write 2–4 sentences: who you are, years of experience, tools or equipment you used, and the value you can bring. Example: “CNC operator with 4 years of experience. I work with Fanuc and Heidenhain, read technical drawings and perform dimensional checks.”',skills:'Use concrete skills, equipment, software, certificates and licences. “Fanuc, Heidenhain, CMM, forklift licence” is stronger than only “responsible”.',languages:'Add a level for every language: A1–C2 or native. Example: “Ukrainian — native, Slovak — B1, English — A2”.',position:'Use a specific target job title, e.g. “CNC operator”, “Welder”, “Warehouse worker / forklift”. This improves job matching.',experience:'Describe outcomes, not only duties: equipment, materials, work volume, quality, speed or responsibility. Formula: action + tool/equipment + result.',education:'Add institution, specialization and year. Courses, certificates and licences can also be mentioned under skills or profile.'}}
};
function lang(){var l=(localStorage.getItem('jobaiLanguage')||document.documentElement.lang||'ua').toLowerCase();return l.indexOf('sk')===0?'sk':l.indexOf('en')===0?'en':'ua';}
function make(id,key){var el=document.getElementById(id);if(!el||document.querySelector('[data-jobai-hint="'+id+'"]'))return;var d=document.createElement('div');d.className='jobai-resume-hint';d.setAttribute('data-jobai-hint',id);d.setAttribute('data-key',key);el.insertAdjacentElement('afterend',d);}
function addExperienceHints(){document.querySelectorAll('#experienceContainer .entry').forEach(function(entry){if(entry.querySelector('.jobai-exp-hint'))return;var h=document.createElement('div');h.className='jobai-resume-hint jobai-exp-hint';h.setAttribute('data-key','experience');entry.insertBefore(h,entry.firstChild.nextSibling);});document.querySelectorAll('#educationContainer .entry').forEach(function(entry){if(entry.querySelector('.jobai-edu-hint'))return;var h=document.createElement('div');h.className='jobai-resume-hint jobai-edu-hint';h.setAttribute('data-key','education');entry.insertBefore(h,entry.firstChild.nextSibling);});}
function translate(){var x=T[lang()];document.querySelectorAll('.jobai-resume-hint').forEach(function(h){var k=h.getAttribute('data-key');h.innerHTML='<strong>💡 '+x.title+':</strong> '+x[k]+' <span class="jobai-hint-truth">'+x.truth+'</span>';});}
function build(){make('position','position');make('profile','profile');make('skills','skills');make('languages','languages');addExperienceHints();translate();if(!document.getElementById('jobaiResumeHintsStyle')){var s=document.createElement('style');s.id='jobaiResumeHintsStyle';s.textContent='.jobai-resume-hint{margin-top:7px;padding:10px 12px;border-left:3px solid #60a5fa;border-radius:8px;background:rgba(59,130,246,.09);color:#cbd5e1;font-size:13px;line-height:1.45}.jobai-resume-hint strong{color:#e2e8f0}.jobai-hint-truth{display:block;margin-top:4px;opacity:.78;font-style:italic}';document.head.appendChild(s);} }
var oldLang=window.setLanguage;window.setLanguage=function(l){if(typeof oldLang==='function')oldLang(l);setTimeout(translate,30);};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
new MutationObserver(function(){addExperienceHints();translate();}).observe(document.documentElement,{childList:true,subtree:true});
})();