/* JobAI — tailor resume to vacancy v1 */
(function(){
'use strict';
var T={ua:{btn:'🎯 Адаптувати резюме під вакансію',title:'Як адаптувати резюме',intro:'JobAI не вигадує досвід. Нижче — лише підказки на основі вашого резюме та тексту вакансії.',matched:'Що варто підкреслити',missing:'Що перевірити',position:'Посада',profile:'Профіль',skills:'Навички',none:'Явних збігів поки не знайдено.',truth:'Додавайте у резюме тільки те, що справді вмієте або робили.'},sk:{btn:'🎯 Prispôsobiť životopis pracovnej ponuke',title:'Ako prispôsobiť životopis',intro:'JobAI si nevymýšľa skúsenosti. Nižšie sú iba odporúčania podľa vášho životopisu a textu ponuky.',matched:'Čo zvýrazniť',missing:'Čo skontrolovať',position:'Pozícia',profile:'Profil',skills:'Zručnosti',none:'Zatiaľ sa nenašli jasné zhody.',truth:'Do životopisu pridávajte iba to, čo skutočne ovládate alebo ste robili.'},en:{btn:'🎯 Tailor resume to job',title:'How to tailor your resume',intro:'JobAI does not invent experience. These suggestions use only your resume and the vacancy text.',matched:'What to emphasize',missing:'What to check',position:'Position',profile:'Profile',skills:'Skills',none:'No clear matches found yet.',truth:'Only add things you genuinely know or have done.'}};
function lang(){var l=(localStorage.getItem('jobaiLanguage')||document.documentElement.lang||'ua').toLowerCase();return l.indexOf('sk')===0?'sk':l.indexOf('en')===0?'en':'ua';}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9+#а-яіїєґ\s-]/gi,' ').replace(/\s+/g,' ').trim();}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function val(id){var e=document.getElementById(id);return e&&e.value?e.value:'';}
function words(s){var stop=['the','and','with','for','you','your','are','praca','prace','pracovne','ponuka','pozadujeme','vyhodou','або','для','робота','досвід','and','work'];return norm(s).split(/\s+/).filter(function(w){return w.length>2&&stop.indexOf(w)<0;});}
function unique(a){return a.filter(function(x,i){return a.indexOf(x)===i;});}
function analyze(){var x=T[lang()],job=val('jobText')||val('job'),resume=[val('position'),val('profile'),val('skills'),val('languages')].join(' ');if(Array.isArray(window.experiences))resume+=' '+JSON.stringify(window.experiences);var jw=unique(words(job)),rw=unique(words(resume)),matched=jw.filter(function(w){return rw.indexOf(w)>=0;}).slice(0,12),missing=jw.filter(function(w){return rw.indexOf(w)<0;}).slice(0,10);var old=document.getElementById('jobaiTailorResult');if(old)old.remove();var box=document.createElement('div');box.id='jobaiTailorResult';box.innerHTML='<h3>'+x.title+'</h3><p>'+x.intro+'</p><div class="jrt-grid"><section><strong>✅ '+x.matched+'</strong><p>'+(matched.length?matched.map(esc).join(', '):x.none)+'</p></section><section><strong>🔎 '+x.missing+'</strong><p>'+(missing.length?missing.map(esc).join(', '):'—')+'</p></section></div><div class="jrt-actions"><p><b>'+x.position+':</b> '+esc(val('position')||'—')+'</p><p><b>'+x.profile+':</b> '+(matched.length?esc(matched.slice(0,5).join(', ')):'—')+'</p><p><b>'+x.skills+':</b> '+(matched.length?esc(matched.join(', ')):'—')+'</p></div><p class="jrt-truth">⚠️ '+x.truth+'</p>';var result=document.getElementById('analysisResult')||document.getElementById('analysis');result.appendChild(box);box.scrollIntoView({behavior:'smooth',block:'center'});}
function build(){var area=document.getElementById('analysisResult')||document.getElementById('analysis');if(!area||document.getElementById('jobaiTailorBtn'))return;var b=document.createElement('button');b.type='button';b.id='jobaiTailorBtn';b.className='btn primary';b.textContent=T[lang()].btn;b.addEventListener('click',analyze);area.parentNode.insertBefore(b,area);if(!document.getElementById('jobaiTailorStyle')){var s=document.createElement('style');s.id='jobaiTailorStyle';s.textContent='#jobaiTailorBtn{margin:12px 0}.jrt-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0}.jrt-grid section,.jrt-actions{padding:12px;border-radius:12px;background:rgba(59,130,246,.08)}#jobaiTailorResult{margin-top:16px;padding:16px;border:1px solid rgba(127,127,127,.3);border-radius:14px}.jrt-truth{font-size:13px;opacity:.8}@media(max-width:650px){.jrt-grid{grid-template-columns:1fr}}';document.head.appendChild(s);}}
var old=window.setLanguage;window.setLanguage=function(l){if(typeof old==='function')old(l);setTimeout(function(){var b=document.getElementById('jobaiTailorBtn');if(b)b.textContent=T[lang()].btn;},30);};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();